version: "3.7"
services:
  ##########################################
  ##  Network Load Balancer for Services  ##
  ##########################################
  network-lb:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - /home/sinless777/services/nginx:/data
      - /home/sinless777/services/nginx/letsencrypt:/etc/letsencrypt

  ##########################
  ##  Network Controller  ##
  ##########################

  unifi:
    image: linuxserver/unifi-controller
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=4096 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
        - unifi:/config
    ports:
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"

  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "8090:8080"
      - "50000:50000"

  heimdall:
    image: linuxserver/heimdall
    ports:
      - "3080:80"
      - "3443:443"
    volumes:
        - heimdall:/config

  #######################
  ##  Message Brokers  ##
  #######################

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data

  #################
  ##  Databases  ##
  #################

  mysql-minecraft-db:
    image: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: klhjflksdlkjsdifuivkwk;lj5u04o23-0588r203082-7rwe52joisdvyxzd9to,3o4ug509e89,ky
        MYSQL_DATABASE: minecraft
        MYSQL_USER: minecraft
        MYSQL_PASSWORD: ankdl;fgs;fl][xzvc[bipo[jwm;'epsa]fujiv,./swmedi[opusdf0ik43570-91[,lkk'ADFcld]gktwu34923
    ports:
      - "3306:3306"

  mysql-helix-db:
    image: mysql
    volumes:
      - mysql-db1:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: kjhsdapgjmw4l;5n mtrupi7usdfoaisyu7g9834875'7y;'[;]o,h[]p;!#$@&*%^$&TGVKD%RS&^TGYI*&$%(yhhsydfa
        MYSQL_DATABASE: helix
        MYSQL_USER: helix
        MYSQL_PASSWORD: kgdfoysyfhwi45u0-270y7970865&^$%@%$#^%Tiubhsgdfkhat7youGFI&^tUHbg8765tghfbuywo3j4uj[;l
    ports:
      - "3307:3306"

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /home/sinless777/services/mysql-db2:/var/lib/mysql

  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    deploy:
      replicas: 6

  mobius:
    image: sinless777/mobius_gateway
    deploy:
      replicas: 6

  #################
  ##  Minecraft  ##
  #################

  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "MOHIST"
      TZ: "America/Denver"
      VERSION: "1.18.2"
      MEMORY: "10G"

    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8804:8804"
      - "5672:5672"
    volumes:
      - minecraft:/data

  banmanager:
    image: sinless777/ban-manager:latest
    depends_on:
      - minecraft
    environment:
      - SERVER_FOOTER_NAME=MobiusInfernium
      - NODE_ENV=production
      - CONTACT_EMAIL=disdainful777@gmail.com
      - ENCRYPTION_KEY=3ea43869c9f887c1d6f0faa7d5af94856d6f1ad17bc739992c5ec5d408f7c68d
      - SESSION_KEY=2acd18005741083fae1fbfbc3de0c60cc8b2049ebb635ffa2933924796986b2c
      - NOTIFICATION_VAPID_PUBLIC_KEY=BO5rcaNwruP03QedGp7uRCrWuUVDs72YsmGjmOsKr5e8Apf87xyw5lEDaweATJOA3oqeH-Xv7FqieUvTiB7NZA8
      - NOTIFICATION_VAPID_PRIVATE_KEY=WbrJftww3b8_RB6hiU-oof-06yoQj9ymvd-PUg4L6hE
      - DB_HOST=192.168.86.40
      - DB_PORT=3306
      - DB_USER=Admin
      - DB_PASSWORD=Shellshocker93
      - DB_NAME=Minecraft_Ban_Manager
    deploy:
      replicas: 4

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  mysql-db:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql-db
      o: bind

  mysql-db1:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql-db1
      o: bind

  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

  minecraft:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/minecraft
      o: bind

  redis:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/cache/redis
      o: bind

