version: "3.9"
services:
  ##########################################
  ##  Network Load Balancer for Services  ##
  ##########################################
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - mysql_data1:/var/lib/mysql


  ##########################
  ##  Network Controller  ##
  ##########################

  unifi:
    image: linuxserver/unifi-controller
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=4096 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - unifi:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      replicas: 3

  heimdall:
    image: linuxserver/heimdall
    privileged: true
    ports:
      - "3443:443"
      - "3081:80"
    volumes:
      - heimdall:/config

  memcached:
    image: 'bitnami/memcached:latest'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      replicas: 3

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      replicas: 3


  #########################
  ##  Tyler's WordPress  ##
  #########################
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8183:80'

  iconiclastart:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    deploy:
      replicas: 3

  #################################
  ###                           ###
  ###   Mobius Infernium | MC   ###
  ###                           ###
  #################################

  mobius:
    image: sinless777/mobius_gateway:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      replicas: 3

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

  mobius:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mobius
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/iconiclast-art
      o: bind
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/iconiclast-art/mysql
      o: bind
  mysql_data1:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql/nginx-proxy
      o: bind

