version: "3.7"
services:
  ##########################################
  ##  Network Load Balancer for Services  ##
  ##########################################
  network-lb:
    image: sinless777/network-lb:1.35
    ports:
      - "443:443"
    depends_on:
      - jenkins
      - mobius
      - sinlessgames
      - heimdall

  ##########################
  ##  Network Controller  ##
  ##########################

  unifi:
    image: linuxserver/unifi-controller
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=4096 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
        - unifi:/config
    ports:
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"

  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "50000:50000"

  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - nagiosetc:/opt/nagios/etc
      - nagiosvar:/opt/nagios/var
      - customplugins:/opt/Custom-Nagios-Plugins
      - nagiosgraphvar:/opt/nagiosgraph/var
      - nagiosgraphetc:/opt/nagiosgraph/etc
    ports:
        - "8081:80"
        - "5666:5666"

  heimdall:
    image: linuxserver/heimdall
    ports:
      - "3080:80"
      - "3443:443"
    volumes:
        - heimdall:/config

  #################
  ##  Databases  ##
  #################

  mysql-minecraft-db:
    image: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: klhjflksdlkjsdifuivkwk;lj5u04o23-0588r203082-7rwe52joisdvyxzd9to,3o4ug509e89,ky
        MYSQL_DATABASE: minecraft
        MYSQL_USER: minecraft
        MYSQL_PASSWORD: ankdl;fg's;fl][xzvc[bipo[jwm;'epsa]fujiv,./swmedi[opusdf0ik43570-91[,lkk'ADFcld]gktwu34923'
    ports:
      - "3306:3306"

  mysql-helix-db:
    image: mysql
    volumes:
      - mysql-db1:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: kjhsdapgjmw4l;5n mtrupi7usdfoaisyu7g9834875'7y;'[;]o,h[]p;!#$@&*%^$&TGVKD%RS&^TGYI*&$%(yhhsydfa
        MYSQL_DATABASE: helix
        MYSQL_USER: helix
        MYSQL_PASSWORD: kgdfoysyfhwi45u0-270y7970865&^$%@%$#^%Tiubhsgdfkhat7youGFI&^tUHbg8765tghfbuywo3j4uj[;l
    ports:
      - "3307:3306"

  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    deploy:
      replicas: 6

  mobius:
    image: sinless777/mobius_gateway
    deploy:
      replicas: 6

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  mysql-db:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql-db
      o: bind

  mysql-db1:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql-db1
      o: bind

  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

  nagiosetc:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nagios/etc
      o: bind

  nagiosvar:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nagios/var
      o: bind

  customplugins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nagios/customplugins
      o: bind

  nagiosgraphvar:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nagiosgraph/var
      o: bind

  nagiosgraphetc:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nagiosgraph/etc
      o: bind