version: "3.7"
services:
  ##########################################
  ##  Network Load Balancer for Services  ##
  ##########################################
  network-lb:
    image: sinless777/network_lb:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    depends_on:
      - jenkins
      - mobius
      - sinlessgames
      - heimdall
      - unifi
      - iconiclastart


  ##########################
  ##  Network Controller  ##
  ##########################

  unifi:
    image: linuxserver/unifi-controller
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=4096 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - unifi:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"

  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "50000:50000"

  heimdall:
    image: linuxserver/heimdall
    privileged: true
    ports:
      - "3443:443"
      - "3081:80"
    volumes:
      - heimdall:/config


  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    deploy:
      replicas: 2

  iconiclastart:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: Admin
      WORDPRESS_DB_PASSWORD: Shellshocker93
      WORDPRESS_DB_NAME: Iconiclast-Art
    volumes:
      - wordpress:/var/www/html

  #################################
  ###                           ###
  ###   Mobius Infernium | MC   ###
  ###                           ###
  #################################

  mobius:
    image: sinless777/mobius_gateway:latest
    deploy:
      replicas: 2

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

  mobius:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mobius
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/iconiclast-art
      o: bind
